webapp/rdb/urls.py
from django.urls import path, include

from rdb.views import actors, index, movies, producers, spouses

app_name = 'rdb'


class Patterns:
    def __init__(self, view):
        self.patterns = [
            path('', view.list, name='list'),
            path('new/', view.create().as_view(), name='create'),
            path('edit/<int:pk>/', view.update().as_view(), name='edit'),
            path(f'delete/<int:element_id>/', view.delete, name='delete'),
        ]


movies_patterns = Patterns(movies).patterns
actors_patterns = Patterns(actors).patterns
spouses_patterns = Patterns(spouses).patterns
producers_patterns = Patterns(producers).patterns

movies_patterns.append(path('actors/<int:movie_id>/', movies.actors, name='actors'))

urlpatterns = [
    path('', index, name='index'),
    path('movies/', include((movies_patterns, 'movies'))),
    path('actors/', include((actors_patterns, 'actors'))),
    path('spouses/', include((spouses_patterns, 'spouses'))),
    path('producers/', include((producers_patterns, 'producers'))),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rdb.urls')),
    # path('admin/', admin.site.urls),
]

webapp/rdb/models.py
from django.db import models
from django.utils import timezone


class Actor(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=1, choices=[('F', 'Female'), ('M', 'Male')])
    birthdate = models.DateField(default=timezone.now)
    spouse = models.OneToOneField('Spouse', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}"


class Spouse(models.Model):
    name = models.CharField(max_length=50)
    birthdate = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.name}"


class Movie(models.Model):
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    producer = models.ForeignKey('Producer', on_delete=models.SET_NULL, null=True)
    actors = models.ManyToManyField(Actor)

    def __str__(self):
        return f"{self.name}"


class Producer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    networth = models.IntegerField()

    def __str__(self):
        return f"{self.name}"

webapp/rdb/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy

from rdb.models import Actor, Movie, Producer, Spouse


def index(request):
    return render(request, 'index.html', {})


class View:
    def __init__(self, cls, name, fields):
        self.cls = cls
        self.name = name
        self.fields = fields

    def list(self, request):
        return render(request, f'{self.name}/list.html', {f'{self.name}': self.cls.objects.all()})

    def delete(self, request, element_id):
        if request.method == 'POST':
            self.cls.objects.get(id=element_id).delete()
        return redirect(reverse_lazy(f'rdb:{self.name}:list'))

    def create(self):
        class Create(CreateView):
            model = self.cls
            fields = self.fields
            template_name = f'{self.name}/create.html'

            @staticmethod
            def get_success_url(*args, **kwargs):
                return reverse_lazy(f'rdb:{self.name}:list')

        return Create

    def update(self):
        class Update(UpdateView):
            model = self.cls
            fields = self.fields
            template_name = f'{self.name}/edit.html'

            @staticmethod
            def get_success_url(*args, **kwargs):
                return reverse_lazy(f'rdb:{self.name}:list')

        return Update


class MovieView(View):
    def __init__(self, *args):
        super().__init__(*args)

    @staticmethod
    def actors(request, movie_id):
        return render(request, f'actors/list.html',
                {'actors': Actor.objects.filter(movie=movie_id)})


movies = MovieView(Movie, 'movies', ['name', 'year', 'producer', 'actors']) 
actors = View(Actor, 'actors', ['name', 'gender', 'birthdate', 'spouse'])
spouses = View(Spouse, 'spouses', ['name', 'birthdate'])
producers = View(Producer, 'producers', ['name', 'address', 'networth'])

webapp/rdb/templates/actors/base.html
{% include "base.html" %}

<h2><a href="{% url 'rdb:actors:list' %}">Actors</a></h2>

webapp/rdb/templates/actors/create.html
{% include "actors/base.html" %}

<h3>Add new actor</h3>

{% include "form.html" %}

webapp/rdb/templates/actors/edit.html
{% include "actors/base.html" %}

<h3>Edit actor</h3>

{% include "form.html" %}

webapp/rdb/templates/actors/list.html
{% include "actors/base.html" %}

{% if actors %}

<table>
	<tr>
		<th>Name</th>
		<th>Gender</th>
		<th>Birthdate</th>
		<th>Spouse</th>
	</tr>
	{% for actor in actors %}
	<tr>
		<td><a href="{% url 'rdb:actors:edit' actor.id %}">{{ actor.name }}</a></td>
		<td>{{ actor.gender }}</td>
		<td>{{ actor.birthdate }}</td>
		<td>{{ actor.spouse }}</td>
		<td class="no-border"><form method="POST" action="{% url 'rdb:actors:delete' actor.id %}">
			{% csrf_token %}
			<button>Delete</button>
		</form></td>
	</tr>
	{% endfor %}

{% else %}
<p>No actors</p>
{% endif %}

<p><a href="{% url 'rdb:actors:create' %}">Add new</a></p>

webapp/rdb/templates/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'rdb/style.css' %}">

<h1><a href="{% url 'rdb:index' %}">Home</a></h1>

webapp/rdb/templates/create.html
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="Create"/>
</form>

webapp/rdb/templates/form.html
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="Create"/>
</form>

webapp/rdb/templates/index.html
<h1> Welcome! </h1>

<ul>
	<li><a href="{% url 'rdb:movies:list' %}">Movies</a></li>
	<li><a href="{% url 'rdb:actors:list' %}">Actors</a></li>
	<li><a href="{% url 'rdb:spouses:list' %}">Spouses</a></li>
	<li><a href="{% url 'rdb:producers:list' %}">Producers</a></li>
</ul>

webapp/rdb/templates/movies/base.html
{% include "base.html" %}

<p><a href="{% url 'rdb:movies:list' %}">Movies</a></p>

webapp/rdb/templates/movies/create.html
{% include "movies/base.html" %}

<h3>Add new movie</h3>

{% include "form.html" %}

webapp/rdb/templates/movies/edit.html
{% include "movies/base.html" %}

<h3>Edit movie</h3>

{% include "form.html" %}

webapp/rdb/templates/movies/list.html
{% include "movies/base.html" %}

{% if movies %}

<table>
	<tr>
		<th>Name</th>
		<th>Year</th>
		<th>Producer</th>
		<th>Actors</th>
	</tr>
	{% for movie in movies %}
	<tr>
		<td><a href="{% url 'rdb:movies:edit' movie.id %}">{{ movie.name }}</a></td>
		<td>{{ movie.year }}</td>
		<td>{{ movie.producer }}</td>
		<td><a href="{% url 'rdb:movies:actors' movie.id %}">list</a></td>
		<td class="no-border"><form method="POST" action="{% url 'rdb:movies:delete' movie.id %}">
			{% csrf_token %}
			<button>Delete</button>
		</form></td>
	</tr>
	{% endfor %}

{% else %}
<p>No movies</p>
{% endif %}

<p><a href="{% url 'rdb:movies:create' %}">Add new</a></p>

webapp/rdb/templates/producers/base.html
{% include "base.html" %}

<h2><a href="{% url 'rdb:producers:list' %}">Producers</a></h2>

webapp/rdb/templates/producers/create.html
{% include "producers/base.html" %}

<h3>Add new producer</h3>

{% include "create.html" %}

webapp/rdb/templates/producers/edit.html
{% include "producers/base.html" %}

<h3>Edit producer</h3>

{% include "form.html" %}

webapp/rdb/templates/producers/list.html
{% include "producers/base.html" %}

{% if producers %}

<table>
	<tr>
		<th>Name</th>
		<th>Address</th>
		<th>Networth</th>
	</tr>
	{% for producer in producers %}
	<tr>
		<td><a href="{% url 'rdb:producers:edit' producer.id %}">{{ producer.name }}</a></td>
		<td>{{ producer.address }}</td>
		<td>{{ producer.networth }}</td>
		<td class="no-border"><form method="POST" action="{% url 'rdb:producers:delete' producer.id %}">
			{% csrf_token %}
			<button>Delete</button>
		</form></td>
	</tr>
	{% endfor %}

{% else %}
<p>No producers</p>
{% endif %}

<p><a href="{% url 'rdb:producers:create' %}">Add new</a></p>

webapp/rdb/templates/spouses/base.html
{% include "base.html" %}

<h2><a href="{% url 'rdb:spouses:list' %}">Spouses</a></h2>

webapp/rdb/templates/spouses/create.html
{% include "spouses/base.html" %}

<h3>Add new spouse</h3>

{% include "form.html" %}

webapp/rdb/templates/spouses/edit.html
{% include "spouses/base.html" %}

<h3>Edit spouse</h3>

{% include "form.html" %}

webapp/rdb/templates/spouses/list.html
{% include "spouses/base.html" %}

{% if spouses %}

<table>
	<tr>
		<th>Name</th>
		<th>Birthdate</th>
	</tr>
	{% for spouse in spouses %}
	<tr>
		<td><a href="{% url 'rdb:spouses:edit' spouse.id %}">{{ spouse.name }}</a></td>
		<td>{{ spouse.birthdate }}</td>
		<td class="no-border"><form method="POST" action="{% url 'rdb:spouses:delete' spouse.id %}">
			{% csrf_token %}
			<button>Delete</button>
		</form></td>
	</tr>
	{% endfor %}

{% else %}
<p>No spouses</p>
{% endif %}

<p><a href="{% url 'rdb:spouses:create' %}">Add new</a></p>